user_index:
    path: /api/v1/users
    controller: App\Controller\Api\UserController::index
    methods: [GET]

user_create:
    path: /api/v1/users
    controller: App\Controller\Api\UserController::create
    methods: [POST]

user_show:
    path: /api/v1/users/{id}
    controller: App\Controller\Api\UserController::show
    methods: [GET]

user_update:
    path: /api/v1/users/{id}
    controller: App\Controller\Api\UserController::update
    methods: [PUT]

user_delete:
    path: /api/v1/users/{id}
    controller: App\Controller\Api\UserController::delete
    methods: [DELETE]